#!/bin/sh

prefix=/usr
exec_prefix=/usr
exec_prefix_set=no

usage()
{
	cat <<EOF
Usage: glib-config [OPTIONS] [LIBRARIES]
Options:
	[--prefix[=DIR]]
	[--exec-prefix[=DIR]]
	[--version]
	[--libs]
	[--cflags]
Libraries:
	glib
	gmodule
	gthread
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi

lib_glib=yes

cmd="pkg-config "

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo_prefix=yes
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo_exec_prefix=yes
      ;;
    --version)
      echo 1.2.10
      exit 0
      ;;
    --cflags | --libs)
      cmd="$cmd $1 "
      echo_pkgconfig="yes"
      ;;
    glib | gmodule | gthread)
      cmd="$cmd $1 "
      echo_pkgconfig="yes"
      module_provided="yes"
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

if test "$echo_prefix" = "yes"; then
	echo $prefix
fi
if test "$echo_exec_prefix" = "yes"; then
	echo $exec_prefix
fi
if test "$echo_pkgconfig" = "yes"; then
        if test -z "$module_provided" ; then
                cmd="$cmd glib"
        fi
	echo `$cmd`
fi
